//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvContent
    {
        public long AdvContentId { get; set; }
        public string ImgUrl { get; set; }
        public string Link { get; set; }
        public string Target { get; set; }
        public Nullable<int> AdvId { get; set; }
    
        public virtual Adv Adv { get; set; }
    }
}
