//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long ArticleId { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleDescription { get; set; }
        public string ArticleContent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsNewHot { get; set; }
        public string ArticleImageSmall { get; set; }
        public string ArticleImageBig { get; set; }
        public string SlugArticleTitle { get; set; }
        public string Tags { get; set; }
        public string TypePost { get; set; }
        public string StatusPost { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<bool> Published { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
    }
}
