//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigId { get; set; }
        public string PageTitle { get; set; }
        public string PageDescription { get; set; }
        public string BgColorHeader { get; set; }
        public string BgImageHeader { get; set; }
        public string BgColorPanel { get; set; }
        public string BgImagePanel { get; set; }
        public string BgColorFooter { get; set; }
        public string BgImageFooter { get; set; }
        public string FooterContent { get; set; }
    }
}
