//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongChuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongChuc()
        {
            this.DanhGiaCongChucs = new HashSet<DanhGiaCongChuc>();
        }
    
        public long CongChucId { get; set; }
        public string TenCongChuc { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string TrinhDo { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<bool> Published { get; set; }
    
        public virtual DonVi DonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaCongChuc> DanhGiaCongChucs { get; set; }
    }
}
