//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Embed
    {
        public int EmbedId { get; set; }
        public string EmbedName { get; set; }
        public string EmbedFile { get; set; }
        public Nullable<bool> EmbedOption { get; set; }
        public string EmbedContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
