//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiDapCauHois
    {
        public long CauHoiId { get; set; }
        public string TenCauHoi { get; set; }
        public string NoiDungCauHoi { get; set; }
        public Nullable<System.DateTime> NgayHoiDap { get; set; }
        public Nullable<bool> TrangThaiCauHoi { get; set; }
        public Nullable<int> LinhVucHoiDapId { get; set; }
        public string DonViTiepNhanId { get; set; }
        public string HoTenNguoiHoi { get; set; }
        public string DiaChiNguoiHoi { get; set; }
        public string SoDienThoaiNguoiHoi { get; set; }
        public string EmailNguoiGui { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public string TDTraLoi { get; set; }
        public string NDTraLoi { get; set; }
        public Nullable<System.DateTime> NgayTraLoi { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual HoiDapLinhVuc HoiDapLinhVuc { get; set; }
    }
}
