//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoiDapLinhVuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoiDapLinhVuc()
        {
            this.HoiDapCauHois = new HashSet<HoiDapCauHois>();
            this.HoiDapLinhVucs1 = new HashSet<HoiDapLinhVuc>();
        }
    
        public int LinhVucId { get; set; }
        public string TenLinhVuc { get; set; }
        public string DiaChiTruyCap { get; set; }
        public Nullable<int> LinhVucChaId { get; set; }
        public Nullable<int> ViTriLinhVuc { get; set; }
        public Nullable<bool> Published { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoiDapCauHois> HoiDapCauHois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoiDapLinhVuc> HoiDapLinhVucs1 { get; set; }
        public virtual HoiDapLinhVuc HoiDapLinhVuc1 { get; set; }
    }
}
