//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKet
    {
        public int LienKetId { get; set; }
        public string LienKetName { get; set; }
        public string LienKetUrl { get; set; }
        public Nullable<bool> IsOption { get; set; }
        public string ImageUrl { get; set; }
        public string Target { get; set; }
    }
}
