//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinhVuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinhVuc()
        {
            this.DanhGiaDonVis = new HashSet<DanhGiaDonVi>();
        }
    
        public int LinhVucId { get; set; }
        public string TenLinhVuc { get; set; }
        public Nullable<int> DonViId { get; set; }
        public Nullable<int> PositionIndex { get; set; }
        public Nullable<bool> Published { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaDonVi> DanhGiaDonVis { get; set; }
        public virtual DonVi DonVi { get; set; }
    }
}
