//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleLink { get; set; }
        public Nullable<bool> HiddenModuleName { get; set; }
        public string TypeModule { get; set; }
        public string Position { get; set; }
        public Nullable<int> PositionIndex { get; set; }
        public Nullable<bool> Published { get; set; }
    }
}
