//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int SupportId { get; set; }
        public string SupportType { get; set; }
        public string SupportContent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public Nullable<bool> SendedEmail { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
