//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTinTuc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebTinTucEntities : DbContext
    {
        public WebTinTucEntities()
            : base("name=WebTinTucEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessStatistic> AccessStatistics { get; set; }
        public virtual DbSet<AdvContent> AdvContents { get; set; }
        public virtual DbSet<Adv> Advs { get; set; }
        public virtual DbSet<AlbumImage> AlbumImages { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AttachModel> AttachModels { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ConfigAccount> ConfigAccounts { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<CongChuc> CongChucs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DanhGiaCongChuc> DanhGiaCongChucs { get; set; }
        public virtual DbSet<DanhGiaDonVi> DanhGiaDonVis { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetails { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<Embed> Embeds { get; set; }
        public virtual DbSet<HoiDapCauHois> HoiDapCauHois { get; set; }
        public virtual DbSet<HoiDapLinhVuc> HoiDapLinhVucs { get; set; }
        public virtual DbSet<LienKet> LienKets { get; set; }
        public virtual DbSet<LinhVuc> LinhVucs { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Lydo> Lydoes { get; set; }
        public virtual DbSet<Map> Maps { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Support> Supports { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    }
}
